#!/bin/bash
set -e

# =============================================================================
# Multi-school deploy for schools_website
#
#   ./deploy.sh                # default school (heritage)
#   ./deploy.sh --heritage     # deploy from schools/heritage.json
#   ./deploy.sh --drgwarzo     # deploy from schools/drgwarzo.json
#   ./deploy.sh --list         # list available schools
#
# Each school is configured in schools/<key>.json (single source of truth).
# This script derives .env.production from the JSON (quoting values so #hex
# colours survive dotenv), builds, and deploys to the docroot in the JSON's
# "deploy" section via a chunked SSH pipe (SCP hangs on go54).
# =============================================================================

cd "$(dirname "$0")"

SCHOOLS_DIR="schools"
DEFAULT_SCHOOL="heritage"

SCHOOL=""
for arg in "$@"; do
  case "$arg" in
    --list|-l)
      echo "Available schools:"
      for f in "$SCHOOLS_DIR"/*.json; do
        basename "$f" .json
      done
      exit 0
      ;;
    --*)
      SCHOOL="${arg#--}"
      ;;
  esac
done

[ -z "$SCHOOL" ] && SCHOOL="$DEFAULT_SCHOOL"
JSON="$SCHOOLS_DIR/$SCHOOL.json"

if [ ! -f "$JSON" ]; then
  echo "❌ No config found: $JSON"
  echo "   Available:"
  for f in "$SCHOOLS_DIR"/*.json; do echo "   --$(basename "$f" .json)"; done
  exit 1
fi

if grep -q "FILL_ME" "$JSON"; then
  echo "❌ $JSON still contains FILL_ME placeholders — fill them in before deploying."
  exit 1
fi

echo "🚀 Deploying schools_website → $SCHOOL"
echo "================================================"

# --- Step 0: Generate .env.production from the school JSON --------------------
echo "📋 Step 0: Generating .env.production from $JSON..."
python3 - "$JSON" <<'PY'
import json, sys
cfg = json.load(open(sys.argv[1]))
skip = {'deploy', '__note'}

def esc(v):
    s = str(v)
    s = s.replace('\\', '\\\\').replace('"', '\\"').replace('`', '\\`')
    return '"' + s + '"'

lines = [
    '# =============================================================================',
    '# PRODUCTION environment — AUTO-GENERATED by deploy.sh from ' + sys.argv[1],
    '# Do not edit: any changes will be overwritten on the next deploy.',
    '# =============================================================================',
]
for k, v in cfg.items():
    if k in skip:
        continue
    lines.append(f'VITE_{k.upper()}={esc(v)}')
print('\n'.join(lines) + '\n')
PY
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then
  echo "❌ Failed to generate .env.production"
  exit 1
fi
echo "✅ .env.production generated"

# --- Step 1: Build --------------------------------------------------------------
echo ""
echo "📋 Step 1: Building project..."
npm run build
echo "✅ Build completed (dist/)"

echo ""
echo "📋 Step 2: Ensuring .htaccess is in build output..."
if cp public/.htaccess dist/.htaccess 2>/dev/null; then
  echo "✅ .htaccess ready for SPA routing"
else
  echo "⚠️  .htaccess copy skipped — using Vite's public/ copy"
fi

# --- Step 2: Deploy -------------------------------------------------------------
DEPLOY_SECTION=$(python3 - "$JSON" <<'PY'
import json, sys
d = json.load(open(sys.argv[1])).get('deploy', {})
for k in ('ssh_key', 'ssh_user', 'host', 'path', 'site'):
    print(d.get(k, ''))
PY
)
read -r SSH_KEY SSH_USER HOST DEPLOY_PATH SITE <<< "$(echo "$DEPLOY_SECTION" | tr '\n' ' ')"

if [ -z "$HOST" ] || [ -z "$DEPLOY_PATH" ]; then
  echo "❌ $JSON has no deploy section — nothing to upload."
  exit 1
fi

SSH_KEY="${SSH_KEY/#\~/$HOME}"
SSH_KEY="${GO54_KEY:-$SSH_KEY}"
SSH_USER="${GO54_USER:-$SSH_USER}"
HOST="${GO54_HOST:-$HOST}"
DEPLOY_PATH="${GO54_PATH:-$DEPLOY_PATH}"

if [ ! -f "$SSH_KEY" ]; then
  echo "⚠️  SSH key not found at $SSH_KEY — skipping deploy (build only)."
  echo "    Pass GO54_KEY=/path/to/key to override."
  exit 0
fi

SSH_BASE="ssh -i $SSH_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=20 $SSH_USER@$HOST"
SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=20"

echo ""
echo "📋 Step 3: Deploying to ${HOST}:${DEPLOY_PATH} (via chunked SSH pipe)..."
$SSH_BASE "mkdir -p ${DEPLOY_PATH}"

TAR_FILE="/tmp/${SCHOOL}-deploy.tar.gz"
PARTS_DIR="/tmp/${SCHOOL}-parts"
REMOTE_TAR="/tmp/${SCHOOL}-deploy-$$.tar.gz"
rm -f "$TAR_FILE"
rm -rf "$PARTS_DIR"; mkdir -p "$PARTS_DIR"

echo "  📦 Packing files..."
tar -czf "$TAR_FILE" -C dist .

$SSH_BASE "rm -f $REMOTE_TAR"
echo "  📤 Uploading (chunked)..."
split -b 2000000 "$TAR_FILE" "$PARTS_DIR/part-"
for p in "$PARTS_DIR"/part-*; do
  cat "$p" | $SSH_BASE "cat >> $REMOTE_TAR"
done

LOCAL_SIZE=$(wc -c < "$TAR_FILE" | tr -d ' ')
REMOTE_SIZE=$($SSH_BASE "wc -c < $REMOTE_TAR" 2>/dev/null | tr -d ' ')
echo "  ✅ Transferred $REMOTE_SIZE / $LOCAL_SIZE bytes"
if [ "$LOCAL_SIZE" != "$REMOTE_SIZE" ]; then
  echo "❌ Transfer size mismatch — aborting (nothing extracted)."
  $SSH_BASE "rm -f $REMOTE_TAR"
  rm -rf "$PARTS_DIR" "$TAR_FILE"
  exit 1
fi

echo "  📂 Extracting on server..."
$SSH_BASE "cd $DEPLOY_PATH && tar -xzf $REMOTE_TAR && rm -f $REMOTE_TAR"
rm -rf "$PARTS_DIR" "$TAR_FILE"

echo ""
echo "✅ Deployed to: ${SITE:-$HOST}"

# --- Step 3: Push source ---------------------------------------------------------
echo ""
echo "📋 Step 4: Pushing source to git repository..."

GITHUB_TOKEN="${GITHUB_TOKEN:-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}"
GIT_REPO="https://${GITHUB_TOKEN}@github.com/eliteedtech1-debug/school-website.git"

if git diff --quiet && git diff --cached --quiet; then
  echo "⚠️  No changes to commit — skipping git push"
else
  git add -A
  git commit -m "deploy: update schools_website ($SCHOOL) [skip ci]" 2>/dev/null || echo "⚠️  Nothing new to commit"
  git push "$GIT_REPO" dynamic 2>&1 || echo "⚠️  Git push failed (may need to pull/rebase first)"
  echo "✅ Source pushed to origin"
fi

echo ""
echo "🎉 Deployment completed for $SCHOOL!"
echo "   Site: ${SITE:-$HOST}"
